### ISSUE TITLE
Images not (yet) appearing on github pages

### ISSUE THREAD

**Issue by ColCarroll** [ericmjl/bayesian-deep-learning-demystified#1]
Images not (yet) appearing on https://ericmjl.github.io/bayesian-deep-learning-demystified/

It looks like they're all there, and there's no 404, just they aren't rendering.

**Comment by ericmjl** [comment]
hmmm... over here at work it looks fine. Let me check on another browser.

**Comment by ericmjl** [comment]
Okay, confirmed. Looks like the images are truly not loading. Let me check in with GitHub.

**Comment by ericmjl** [comment]
Hmmm... I just checked - Safari in Incognito mode, things work; in Chrome they don't. This is super weird.

**Comment by ColCarroll** [comment]
issue with pdfs in chrome, maybe?

**Comment by ericmjl** [comment]
I think that might be it. Let me see what happens when I convert them all to SVGs.

**Comment by ericmjl** [comment]
Ok, all fixed. Should work now!
